config/routes.rb
Rails.application.routes.draw do

root 'inputs#index'
get 'inputs' => 'inputs#new', as: :new_input
post 'inputs' => 'inputs#create', as: :inputs
get 'inputs/:id' => 'inputs#show', as: :input
get 'inputs/:id/edit' => 'inputs#edit', as: :edit_input
patch 'inputs/:id' => 'inputs#update'
delete 'inputs/:id' => 'inputs#destroy', as: :destroy_input

end

app/models/input.rb
class Input < ActiveRecord::Base

  validates :name, presence: {message: "Company name must be provided"}

  validates :email, presence: {message: "Email must be provided"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController

  def index
    @input = Input.all
  end

  def new
    @input = Input.new
  end

  def create
    input_params = params.require(:input).permit([:name, :email, :department, :message])
    @input        = Input.new(input_params)
    if @input.save
      redirect_to input_path(@input), notice: "Support Ticket Created"
    else
      render :new
    end
  end

  def show
    @input = Input.find params[:id]
  end

  def edit
    @input = Input.find params[:id]
  end

  def update
    @input = Input.find params[:id]
    input_params = params.require(:input).permit([:name, :email, :department, :message])
    if @input.update(input_params)
      redirect_to input_path(@input), notice: "Support Ticket Updated"
    else
      render :edit
    end
  end

  def destroy
    @input = Input.find params[:id]
    @input.destroy
    redirect_to root_path, notice: "Support Ticket deleted"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/edit.html.erb
<% if @input.errors.any? %>
  <ul>
    <% @input.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @input do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.radio_button(:department, "Sales") %>
    <%= f.label(:department_sales, "Sales") %>
    <%= f.radio_button(:department, "Marketing") %>
    <%= f.label(:department_marketing, "Marketing") %>
    <%= f.radio_button(:department, "Technical") %>
    <%= f.label(:department_marketing, "Technical") %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Add Support Ticket" %>
<% end %>

app/views/inputs/index.html.erb
<h1>Supporter</h1>
<table>
  <tr class="head">
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
    <td>Message</td>
    <td>Actions</td>
  </tr>
<% @input.each do |x| %>
    <tr>
      <td><%= link_to x.name, input_path(x) %></td>
      <td><a href="mailto:<%= x.email %>"><%= x.email %></a></td>
      <td><%= x.department %></td>
      <td><%= x.message %></td>
      <td><%= link_to "Edit", edit_input_path(@input) %> |
          <%= link_to "Delete", input_path(@input),
                    method: :delete, data: {confirm: "Are you sure"} %></td>
    </tr>
<% end %>
</table>

app/views/inputs/new.html.erb
<% if @input.errors.any? %>
  <ul>
    <% @input.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @input do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.radio_button(:department, "Sales") %>
    <%= f.label(:department_sales, "Sales") %>
    <%= f.radio_button(:department, "Marketing") %>
    <%= f.label(:department_marketing, "Marketing") %>
    <%= f.radio_button(:department, "Technical") %>
    <%= f.label(:department_marketing, "Technical") %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Add Support Ticket" %>
<% end %>

app/views/inputs/show.html.erb
<h2><%= @input.name %></h2>
<p><%= @input.email %></p>
<p><%= @input.department %></p>
<p><%= @input.message %></p>

<%= link_to "Edit", edit_input_path(@input) %> | 

<%= link_to "Delete", input_path(@input),
              method: :delete, data: {confirm: "Are you sure"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to "Support Tickets", root_path %> | 
  <%= link_to "New Support Ticket", new_input_path %>

<%= yield %>

</body>
</html>